export default [
{  id: '1',
    price: 1245,
    rating:3,
    src: './img/078294250-childs-bedroom-apartment.jpg',
    description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '32',
price: 300,
rating:4.5,
src: './img/078294663-modern-yellow-and-grey-apartme.jpg',
description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '33',
price: 800,
rating:3.7,
src: './img/194628151-modern-kitchen-interior-apartm.jpg',
description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ips',
},
{  id: '35',
price: 200,
rating:1,
src: './img/194654943-spacious-room-passage-apartmen.jpg',
description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '37',
    price: 1245,
    rating:3,
    src: './img/078294250-childs-bedroom-apartment.jpg',
    description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '38',
price: 300,
rating:4.5,
src: './img/078294663-modern-yellow-and-grey-apartme.jpg',
description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '39',
price: 800,
rating:3.7,
src: './img/194628151-modern-kitchen-interior-apartm.jpg',
description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ips',
},
{  id: '44',
price: 200,
rating:1,
src: './img/194654943-spacious-room-passage-apartmen.jpg',
description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '25',
price: 800,
rating:3.7,
src: './img/194628151-modern-kitchen-interior-apartm.jpg',
description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ips',
},
{  id: '26',
price: 200,
rating:1,
src: './img/194654943-spacious-room-passage-apartmen.jpg',
description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '27',
    price: 1245,
    rating:3,
    src: './img/078294250-childs-bedroom-apartment.jpg',
    description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
{  id: '11',
price: 300,
rating:4.5,
src: './img/078294663-modern-yellow-and-grey-apartme.jpg',
description: 'The IPTC took part in a panel on Diversity and Inclusion at the CEPIC Congress 2022, the picture industry’s ann',
},
]